version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_APP_DOMAIN: ${NEXT_PUBLIC_APP_DOMAIN}
        NEXT_PUBLIC_BETTER_AUTH_URL: ${NEXT_PUBLIC_BETTER_AUTH_URL}
    container_name: hashcodesync_app
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://hcode_prod_usr:5ace782fb8dba068d5541b3029f9acec7705623246dabba3@db:5432/hashcode_sync_db
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - NEXT_PUBLIC_BETTER_AUTH_URL=${NEXT_PUBLIC_BETTER_AUTH_URL}
      - NEXT_PUBLIC_APP_DOMAIN=${NEXT_PUBLIC_APP_DOMAIN}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM=${RESEND_FROM}
      - CRON_SECRET=${CRON_SECRET}
      - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE:-Africa/Porto-Novo}
      - TZ=${TZ:-Africa/Porto-Novo}
      - HOST=0.0.0.0
      - HOSTNAME=0.0.0.0
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    volumes:
      - hashcodesync_uploads:/app/public/uploads
    networks:
      - hashcodesync_net
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hashcode-sync.rule=Host(`${NEXT_PUBLIC_APP_DOMAIN}`)"
      - "traefik.http.routers.hashcode-sync.entrypoints=websecure"
      - "traefik.http.routers.hashcode-sync.tls.certresolver=letsencrypt"
      - "traefik.http.services.hashcode-sync.loadbalancer.server.port=3000"

  db:
    image: postgres:16-alpine
    container_name: hashcodesync_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: hcode_prod_usr
      POSTGRES_PASSWORD: 5ace782fb8dba068d5541b3029f9acec7705623246dabba3
      POSTGRES_DB: hashcode_sync_db
    volumes:
      - hashcodesync_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hcode_prod_usr -d hashcode_sync_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
    networks:
      - hashcodesync_net

volumes:
  hashcodesync_postgres:
  hashcodesync_uploads:

networks:
  hashcodesync_net:
    driver: bridge
  proxy:
    external: true
